CREATE TABLE outbox_events
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    aggregate_type VARCHAR(50)                             NOT NULL,
    aggregate_id   BIGINT                                  NOT NULL,
    event_type     VARCHAR(50)                             NOT NULL,
    payload        TEXT,
    status         VARCHAR(20)                             NOT NULL,
    retry_count    INTEGER                                 NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    processed_at   TIMESTAMP WITHOUT TIME ZONE,
    error_message  TEXT,
    CONSTRAINT pk_outbox_events PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username            VARCHAR(50)                             NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    bio                 TEXT,
    profile_picture_url VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);