CREATE TABLE users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username            VARCHAR(50)                             NOT NULL,
    email               VARCHAR(255)                            NOT NULL,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    bio                 TEXT,
    profile_picture_url VARCHAR(255),
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);