CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    VARCHAR(36)                             NOT NULL,
    post_id    BIGINT,
    comment_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id),
    CONSTRAINT chk_like_target CHECK (
        (post_id IS NOT NULL AND comment_id IS NULL) OR
        (post_id IS NULL AND comment_id IS NOT NULL)
        ),
    CONSTRAINT uq_user_post_like UNIQUE (user_id, post_id),
    CONSTRAINT uq_user_comment_like UNIQUE (user_id, comment_id)
);

CREATE TABLE comments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id           BIGINT                                  NOT NULL,
    user_id           VARCHAR(36)                             NOT NULL,
    parent_comment_id BIGINT,
    content           TEXT                                    NOT NULL,
    is_edited         BOOLEAN                                 NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_parent_comment FOREIGN KEY (parent_comment_id) REFERENCES comments (id) ON DELETE CASCADE
);