CREATE TABLE comments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id           BIGINT                                  NOT NULL,
    user_id           BIGINT                                  NOT NULL,
    parent_comment_id BIGINT,
    content           TEXT                                    NOT NULL,
    is_edited         BOOLEAN                                 NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    post_id    BIGINT,
    comment_id BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE post_media_urls
(
    post_id   BIGINT NOT NULL,
    media_url VARCHAR(255)
);

CREATE TABLE posts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    content    TEXT,
    privacy    VARCHAR(20)                             NOT NULL,
    is_edited  BOOLEAN                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

ALTER TABLE post_media_urls
    ADD CONSTRAINT fk_post_media_urls_on_post FOREIGN KEY (post_id) REFERENCES posts (id);